feat(BUX-147): integrate go-broadcast-client
BuxOrg/bux-server pull request #287
Opened 2023-08-23 12:06 UTC by pawellewandowski98

Description
--------

- Integrate go-broadcast-client

Additional links
-----------

- [Jira task](https://bitcoinassociation.atlassian.net/browse/BUX-147?atlOrigin=eyJpIjoiMWRhNzcxODdjMGVjNDA4YzlmODNmMDQ2ZDVhMjAzOTgiLCJwIjoiaiJ9)
- [BUX PR](https://github.com/BuxOrg/bux/pull/372)

# DO NOT MERGE
#### Wait for BUX PR

2023-08-23 13:32 UTC, mrz1836 requested changes
Tests failed, probably missing the Bux PR.

2023-08-23 13:49 UTC, kuba-4chain approved these changes

2023-08-23 13:52 UTC, pawellewandowski98 commented
> Tests failed, probably missing the Bux PR.

@mrz1836  Yes, when the new BUX version will be released,  I will update it in go.mod and then tests should succeed.

2023-08-24 12:58 UTC, mrz1836 approved these changes
LGTM

2023-08-24 12:59 UTC, merged