Added new utxo endpoints, including the original transaction
BuxOrg/bux-server pull request #91
Opened 2022-06-27 14:18 UTC by icellan

This is still work in progress, needs bux to be updated first

2022-06-27 14:29 UTC, mrz1836 commented on actions/utxos/count.go
> +// get will fetch utxos according to conditions
Wrong comment

2022-06-27 14:32 UTC, mrz1836 commented on config/envs/development.json
> +    "_port": "5432",
Use and env var vs hacking with _

2022-06-27 14:32 UTC, mrz1836 commented on config/envs/development.json
> +    "_user": "postgres"
Use and env var vs hacking with _

2022-06-27 20:53 UTC, mrz1836 requested changes
See my comments

2022-06-30 13:14 UTC, icellan commented on config/envs/development.json
> +    "auth_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzaWdnaSIsImV4cCI6MTc1MDM4MTA2OH0.EXHm4MrwnJGjHIrdSUP39TyQZsieukWivCwqecQO0F8",
WTF?

2022-06-30 13:20 UTC, icellan commented
Squashed the branch with the fixes from the comments you made

2022-06-30 13:38 UTC, mrz1836 approved these changes
LGTM

2022-07-06 15:54 UTC, merged